version: '3.8'

services:
  web:
    image: r0879842/project4.0-bastion-api:latest
    ports:
      - "8080:80"
    environment:
      - AWS_ACCESS_KEY=your_access_key
      - AWS_SECRET_KEY=your_secret_key
      - AWS_REGION=your_s3_region
      - BUCKET_NAME=your_bucket_name
      - DATABASE_URL=postgresql://user:password@your-rds-host:your-rds-port/your-rds-dbname
